# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Change the return code symbols
[character]
success_symbol = '[âœ](bold green)'
error_symbol = '[âœ—](bold red)'

# Adjust prompt to git status
[git_status]
conflicted = "ğŸ’£"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "++"
renamed = "ğŸ‘…"
deleted = "ğŸ«¥"

# Show time
[time]
disabled = false
format = '[$time]($style) '
time_format = '%H:%M'

# Show if sudo credentials are cached
[sudo]
disabled = false

# Disable these
[package]
disabled = true
